nouns = ["Katzen", 
         "Hunde", 
         "Fichten", 
         "Lorbeerzweige", 
         "Akazien", 
         "Holunderblüten", 
         "Wellen", 
         "Bachverläufe", 
         "Tautropfen",
         "Oberflächen",
         "Gefühle",
         "Schlagbohrer",
         "DAX-Vorstände",
         "Menschen",
         "Leben",
         "Augen",
         "Fenster",
         "Kinder",
         "Gedanken",
         "Ideale"]

verbs = ["vergehen", 
         "stöbern", 
         "sprechen", 
         "sterben", 
         "hoffen", 
         "verlieren", 
         "strömen",
         "jauchzen",
         "julbilieren",
         "versagen",
         "sind"]

prepositions = ["in", 
                "unter", 
                "durch", 
                "auf", 
                "hinter", 
                "neben",
                "an",
                "so"]

adjectives = ["grazil", 
              "erhaben", 
              "verwegen", 
              "listig", 
              "hintersinnig", 
              "beschwingt",
              "todesfürchtig",
              "schelmisch",
              "dichten",
              "freudig",
              "entfremdet",
              "mystisch",]

gerunds = ["taumelnden",
           "fließenden",
           "jammernden",
           "brillierenden",
           "jauchzenden",
           "verstörenden",
           "glimmenden",
           "schmachtenden",
           "schlummernden",
           "drohenden",
           "blutenden"]