text_list = [
    "und schießt sich in den Kopf",
    "Den Kopf, das Herz erhellte ein unvorstellbares Licht;",
    "wenn mein Kopf an die Backsteinwand prallte",
    "dass er ein Dach über dem Kopf hat",
    "ich notiere im Kopf das Material für die Nacht",
    "dass es sich bei Lillian nur um ein leichtes Kopfweh handelt",
    "schreibst im Kopf Novellen und Romane",
    "Blick zum Publikum Kopf schütteln",
    "(senkt den Kopf und murmelt)",
    "Mit hochaufgerichtetem Kopf naturgemäß",
    "setzt sich Box auf Kopf",
    "geht kopfschüttelnd, als wäre er beleidigt worden",
    "Wenn ich wüßt, wie es in ihrem Kopf ausschaut!",
    "aber irgendwie herrscht in ihrem Kopf ein großes Durcheinander,",
    "Auch der größte Fisch stinkt immer vom Kopf",
    "die Perücke auf dem Kopf,",
    "sich den Kopf mit Bücherunrat vollzustopfen",
    "Mit hochaufgerichtetem Kopf naturgemäß",
    "Dummkopf",
    "Etwas, das Ihrem Kopf entspringt ",
    "Der wird uns noch dumm, als ging ihm ein Mühlrad im Kopf herum",
    "fallen ganz plötzlich kopfüber um und sind tot",
    "Mit hochaufgerichtetem Kopf naturgemäß",
    "lehnt Kopf auf seine Schulter",
    "Mit hochaufgerichtetem Kopf naturgemäß",
    "Wo steht dein Kopf?",
    "Isabella kommt nach vorne und wirft Jackett über Kaspars Kopf",
    "Mit hochaufgerichtetem Kopf naturgemäß",
    "Hände hinter den Kopf und keine falsche Bewegung",
    "Ein Herz in deinem Kopf!",
    "Uwe wird still mit Kopf/Blick Richtung Zuschauer",
    "daß ich ein zweites Kopfpolster",
    "Gut, geh nur Mit dem Kopf nach hinten",
    "das wird sie den Kopf kosten",
    "lehnt sich mit Kopf dagegen",
    "Hände am Kopf",
    "Wir müssen eben abwarten, wer den dickeren Kopf hat",
    "daß ich ein zweites Kopfpolster",
    "Wir können selber denken! Unser Kopf ist groß genug",
    "Mir will einfach nicht in den Kopf",
    "frisst sich in den Kopf der Schmutz",
    "Wie Kopfschmerzen, eine mörderische Migräne",
    "Mit hochaufgerichtetem Kopf naturgemäß",
    "gibt sich Blut auf die Hand und schmiert es auf Uwes Kopf",
    "Fingerhut zaubert mit Digitoxin Bilder in den Kopf, bevor er dich umbringt",
    "dann immer fester, bis mein Kopf an die Wand des Flurs knallte",
    "Wenn mein Aljoscha auch ein Dummkopf ist,",
    "Katha Hand auf Anjas Kopf,",
    "Laß die Sachen da, Kindskopf!",
    "die Gedanken im Kopf,",
    "Aber seit ein paar Monaten hat er nicht mehr nur Blasen im Kopf,",
    "Du bist ein Dummkopf",
    "Nur in meinem Kopf",
    "Keiner von uns hat sich den Kopf ausgesucht, mit dem wir zur Welt gekommen sind",
    "Der Krutzler überragte die gesamte Reihe um einen Kopf und starrte nicht auf den Boden",
    "Auf den dickeren Kopf kommt es nicht an",
    "Wie ein Mühlrad gehen mir die Gedanken im Kopf herum",
    "die Läufe auf meinen Kopf gerichtet Uwe redet einige Sätze nach",
    "Mein Kopf ist voll von anderen Dingen",
    "FRIEDA: Der Gedanke könnte mir durchaus durch den Kopf gehen",
    "NEWTON (hat Kopfschmerzen) Verflucht …",
    "Kopfstücke",
    "Julia Sessel über Kopf",
    "50 Quallenkopf",
    "Evi senkt Kopf",
    "Der Geringste hingegen presste seinen Kopf gegen das Gitter des Ansaugschachts",
    "Dummkopf",
    "Meine Kopfschmerzen und der Schwindel nahmen auch zu,",
    "philosophisches Gehirn fehlt",
    "dass Ihr Hirn sich irgendetwas zusammenreimt",
    "bohren sich in mein Hirn",
    "Shirneto yak age ga -",
    "Gehirn Fehlt",
    "Gehen ist immer mit Glühirne un SUNN - Glühbirne NUR im SUNN",
    "Keine Schmerzen oder so? Die haben sicher gelogen, die hatte sicher nen Gehirntumor…",
    "Philosophisches Gehirn",
    "Hat dir jetzt endgültig der Teufel ins Hirn g'schissen?"
]
